apiVersion: apps/v1
kind: Deployment
metadata:
  name: live
spec:
  replicas: 1
  selector:
    matchLabels:
      app: live
  template:
    metadata:
      labels:
        app: live
    spec:
      containers:
        - name: live
          image: krishna9304/quizzed_live
          env:
            - name: RABBIT_MQ_AUTH_QUEUE
              value: "auth"
            - name: RABBIT_MQ_MAIL_QUEUE
              value: "mail"
            - name: RABBIT_MQ_QUIZ_QUEUE
              value: "quiz"
            - name: RABBIT_MQ_LIVE_QUEUE
              value: "live"